name: mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  get_it: ^7.2.0
  dio: ^5.0.0
  json_annotation: ^4.8.0
  image_picker: ^0.8.6+2
  shared_preferences: ^2.0.17
  flutter_svg: ^2.0.1
  get: ^4.6.5
  flutter_screenutil: ^5.6.1
  flutter_hooks: ^0.18.6
  get_storage: ^2.0.3
  class_to_map: ^0.0.1
  build_runner: ^2.3.3
  retrofit: ^4.0.1
  retrofit_generator: any
  fluttertoast: ^8.0.8
  email_validator: ^2.1.17
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
